/**
 * Gives a slug (URL /project/<slug>) to the projects created before slugs existed.
 *
 *   node scripts/fillSlugs.js            -> dry run: prints the slugs, writes nothing
 *   node scripts/fillSlugs.js --apply    -> saves them
 *
 * The slug is generated by the model (models/Project.js), exactly as when a project is saved
 * from the back office. Projects that already have one are left untouched.
 */
import 'dotenv/config';
import mongoose from 'mongoose';
import Project from '../models/Project.js';

const APPLY = process.argv.includes('--apply');

try {
    await mongoose.connect((process.env.MONGODB_URI || '').trim());
    console.log(`Base : ${mongoose.connection.name} — ${APPLY ? 'ÉCRITURE' : 'simulation (ajouter --apply pour écrire)'}\n`);

    const projects = await Project.find().sort({ project_title: 1 }).exec();
    const planned = new Set(); // dry run: slugs already given by this run (nothing is saved, so not in the DB yet)
    let filled = 0;

    for (const project of projects) {
        const label = (project.project_title || '').slice(0, 34).padEnd(34);
        if (project.slug) {
            console.log(`${label} /project/${project.slug}  (déjà là)`);
            continue;
        }

        if (APPLY) {
            await project.save(); // the pre('save') hook generates the slug
        } else {
            const base = await Project.makeSlug(project.project_title, project._id);
            let slug = base;
            for (let n = 2; planned.has(slug); n++) slug = `${base}-${n}`;
            project.slug = slug;
            planned.add(slug);
        }
        console.log(`${label} /project/${project.slug}  ← nouveau`);
        filled++;
    }

    console.log(`\n${filled} slug(s) ${APPLY ? 'créés' : 'à créer'}.`);
} finally {
    await mongoose.disconnect();
}
